- name: Check for updates on Linux systems
  hosts: all
  become: yes

  tasks:
    - name: Update package cache (Debian-based)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian' and inventory_hostname in groups['ubuntu']

    - name: Update package cache (RedHat-based)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat' and inventory_hostname in groups['rhel']

    - name: List available updates (Debian-based)
      apt:
        upgrade: yes
        update_cache: yes
        list: yes
      register: available_updates
      when: ansible_os_family == 'Debian' and inventory_hostname in groups['ubuntu']

    - name: List available updates (RedHat-based)
      yum:
        list: updates
      register: available_updates
      when: ansible_os_family == 'RedHat' and inventory_hostname in groups['rhel']

    - name: Display available updates
      debug:
        var: available_updates.stdout_lines
      when: available_updates.stdout_lines | length > 0

    - name: Upgrade all packages (Debian-based)
      apt:
        upgrade: dist
        update_cache: yes
      when: available_updates.stdout_lines | length > 0 and ansible_os_family == 'Debian' and inventory_hostname in groups['ubuntu']

    - name: Upgrade all packages (RedHat-based)
      yum:
        name: "*"
        state: latest
      when: available_updates.stdout_lines | length > 0 and ansible_os_family == 'RedHat' and inventory_hostname in groups['rhel']
