---
  - name: "Playing with Ansible"
    hosts: servers
    tasks:

    - name: "just execute a ls -lrt command"
      shell: "uname -a "
      register: "output"

    - debug: var=output.stdout_lines


